base_url = "https://isserge.github.io"
title = "isserge"
description = "Tech blog about system programming, Rust, blockchain, and more."
default_language = "en"
theme = "terminus"
compile_sass = true
build_search_index = true
taxonomies = [{ name = "tags", feed = true }]

[extra]
author = "Serge"
favicon_emoji = "🦀"

[markdown]
render_emoji = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
style = "inline"
theme = "monokai"

[extra.content_security_policy]
enable = true
allowed_domains = [
    { directive = "script-src-elem", domains = [
        "'self'",
        "cloud.umami.is",
    ] },
    { directive = "connect-src", domains = [
        "'self'",
        "cloud.umami.is",
        "api-gateway.umami.dev",
        "gateway.umami.is",
    ] },
]
