base_url = "https://isserge.github.io"
title = "isserge"
theme = "terminus"
compile_sass = true
build_search_index = true

[markdown]
render_emoji = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
style = "inline"
theme = "monokai"

[extra.content_security_policy]
enable = true
allowed_domains = [
    { directive = "script-src-elem", domains = ["cloud.umami.is"] },
    { directive = "connect-src", domains = ["cloud.umami.is", "api-gateway.umami.dev"] },
]
